/**
 * Represents the input required for the AI operation.
 */
export interface AIInput {
  /**
   * The prompt sent to the AI.
   */
  prompt: string;
  /**
   * Any context or additional information required by the AI.
   */
  context: string;
  /**
   * Any additional parameters required for the AI operation.
   */
  parameters: AIParameters;
}

/**
 * Represents the output generated by the AI operation.
 */
export interface AIOutput {
  /**
   * The generated response from the AI.
   */
  response: string;
  /**
   * Confidence score of the generated response.
   */
  confidence: number;
}

/**
 * Represents the parameters required for the AI operation.
 */
export interface AIParameters {
  /**
   * Controls randomness of the AI’s responses.
   */
  temperature: number;
  /**
   * Maximum length of the generated response.
   */
  maxLength: number;
}

/**
 * Represents an entity in Foundry.
 */
export interface FoundryEntity {
  /**
   * Unique identifier of the entity.
   */
  id: string;
  /**
   * Name of the entity.
   */
  name: string;
  /**
   * Type of entity e.g., character, item.
   */
  type: string;
  /**
   * Any other properties of the entity.
   */
  properties: Record<string, any>;
}