name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20' # or your preferred version

      - name: Install Dependencies
        run: npm install

      - name: Check if version has changed
        id: check_version
        run: node ./check-version.js || exit 0
        continue-on-error: true

      - name: Build Project
        if: steps.check_version.outcome == 'success'
        run: npm run build
      
      - name: Get Version from package.json
        id: get_version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"
      
      - name: Create Release and Upload Assets
        if: steps.check_version.outcome == 'success'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./build/module.json
            ./build/*
          tag_name: ${{ steps.get_version.outputs.version }}
          name: Release ${{ steps.get_version.outputs.version }}
          body: Description of the release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}