name: CI/CD

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20' 

      - name: Check if version has changed
        id: check_version
        run: node ./check-version.js || exit 0
        continue-on-error: true

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        if: steps.check_version.outcome == 'success'
        run: npm run build
      
      - name: Get Version from package.json
        id: get_version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"
      
      - name: Zip Build Directory
        if: steps.check_version.outcome == 'success'
        run: zip -r module.zip ./build
      
      - name: Update Latest Release
        if: steps.check_version.outcome == 'success'
        id: update_latest_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: Latest
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './build/module.json,./module.zip'
          tag: latest
      
      - name: Create Version Release
        if: steps.check_version.outcome == 'success'
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: Release ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './build/module.json,./module.zip'
          tag: ${{ steps.get_version.outputs.version }}
